CMRS/Models/Convict.cs
namespace CMRS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;


    public partial class Convict
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name ="Name Of Convict")]
        public string ConvictName { get; set; }

        [Display(Name ="Convict's Age")]
        public int ConvictAge { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name= "Crime Commmited")]
        public string Offense { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name ="Case Status")]
        public string CaseStatus { get; set; }

        [Display(Name ="Jail Term")]
        [Required]
        public int? JailTerm { get; set; }

        [Display(Name ="Start Date")]
        [Required]
        public DateTime? StartDate { get; set; }

        [Display(Name ="End Date")]
        [Required]
        public DateTime? EndDate { get; set; }

        [StringLength(50)]
        [Display(Name ="Name Of Prison")]
        [Required]
        public string PrisonName { get; set; }


        public byte[] Image { get; set; }
    }
}

CMRS/Controllers/Management/ConvictsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CMRS.Models;
using PagedList;

namespace CMRS.Controllers.Management

{
    public class ConvictsController : Controller
    {
        private CmrsModel db = new CmrsModel();

        // GET: Convicts
        public ActionResult Index(string option, string search, int? pageNumber)
        {

            if (option == "Name")
            {
                return View(db.Convicts.Where(x => x.ConvictName.Contains(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 6));
            }
            else if
                (option == "Offense")
            {
                return View(db.Convicts.Where(x => x.Offense.Contains(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 6));
            }
            else
            {
                return View(db.Convicts.Where(x => x.ConvictName.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 6));
            }
        }

        // GET: Convicts/Details/5
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Convict convict = db.Convicts.Find(id);

           byte[] photodisp = convict.Image;

            return File(photodisp, "Details");


            if (convict == null)
            {
                return HttpNotFound();
            }
   

            return View(convict);
        }

        // GET: Convicts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Convicts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ConvictName,ConvictAge,Offense,CaseStatus,JailTerm,StartDate,EndDate,PrisonName,Image")] Convict convict, HttpPostedFileBase uploadFile)
        {

            if (ModelState.IsValid)
            {
           if (uploadFile != null && uploadFile.ContentLength > 0)
                {
                    convict.Image = new byte[uploadFile.ContentLength];
                    uploadFile.InputStream.Read(convict.Image, 0, uploadFile.ContentLength);
                }
                
   
                    db.Convicts.Add(convict);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            
                
                    return View(convict);
                

            }
        
    

        // GET: Convicts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Convict convict = db.Convicts.Find(id);
            if (convict == null)
            {
                return HttpNotFound();
            }
            return View(convict);
        }

        // POST: Convicts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ConvictName,ConvictAge,Offense,CaseStatus,JailTerm,StartDate,EndDate,PrisonName,Image")] Convict convict, HttpPostedFileBase uploadFile)
        {
            if (ModelState.IsValid)

            {
                if (uploadFile != null && uploadFile.ContentLength > 0)
                {
                    convict.Image = new byte[uploadFile.ContentLength];
                    uploadFile.InputStream.Read(convict.Image, 0, uploadFile.ContentLength);
                }

                db.Entry(convict).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(convict);
        }

        // This method displays convicts details in full
        public ActionResult Fulldet(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Convict convict = db.Convicts.Find(id);
            if (convict == null)
            {
                return HttpNotFound();
            }
            return View(convict);
        }

        //This method prints the convict details

        public ActionResult PrintReport(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Convict convict = db.Convicts.Find(id);
            if (convict == null)
            {
                return HttpNotFound();
            }

            return View(convict);

        }
        // GET: Convicts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Convict convict = db.Convicts.Find(id);
            if (convict == null)
            {
                return HttpNotFound();
            }
            return View(convict);
        }

        // POST: Convicts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Convict convict = db.Convicts.Find(id);
            db.Convicts.Remove(convict);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CMRS/Views/Convicts/Create.cshtml
@model CMRS.Models.Convict

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPag.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Convicts", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Convict</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ConvictName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConvictName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConvictName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConvictAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConvictAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConvictAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Offense, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Offense, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Offense, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaseStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DropDownListFor(model => model.CaseStatus, new List<SelectListItem> {

               new SelectListItem { Text="Pending", Value= "0", Selected=true},
               new SelectListItem { Text="Confirmed", Value="1"},
               new SelectListItem { Text="Not Confirmed", Value="2"}
           }, "--Select Case Status", new { @class="form-control"})
                @Html.ValidationMessageFor(model => model.CaseStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JailTerm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10"> 
                @Html.EditorFor(model => model.JailTerm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JailTerm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrisonName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrisonName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrisonName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Convicts Image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" type="file" id="Image" name="uploadFile" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CMRS/Views/Convicts/Delete.cshtml
@model CMRS.Models.Convict

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPag.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Convict</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConvictName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConvictName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConvictAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConvictAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offense)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offense)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaseStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaseStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JailTerm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JailTerm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrisonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrisonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Action("Details", "Convicts", new { id = Model.Id })" width="50px" height="50px" />

        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CMRS/Views/Convicts/Details.cshtml
@model CMRS.Models.Convict

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPag.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Convict</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConvictName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConvictName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConvictAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConvictAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offense)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offense)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaseStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaseStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JailTerm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JailTerm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrisonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrisonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Action("Details", new { id =Model.Id})" />
</dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CMRS/Views/Convicts/Edit.cshtml
@model CMRS.Models.Convict

@{
    ViewBag.Title = "Edit Convict";
    Layout = "~/Views/Shared/_LayoutPag.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Convicts", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <fieldset>
            <h4>Convict</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.ConvictName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConvictName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ConvictName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConvictAge, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConvictAge, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ConvictAge, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Offense, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Offense, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Offense, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CaseStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownListFor(model => model.CaseStatus, new List<SelectListItem> {

               new SelectListItem {Text="Pending",  Selected=true},
               new SelectListItem { Text="Confirmed" },
               new SelectListItem {   Text="Not Confirmed"}
           }, "--Select Case Status--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CaseStatus, "", new { @class = "text-danger" })
                </div>
            

            <div class="form-group">
                @Html.LabelFor(model => model.JailTerm, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.JailTerm, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.JailTerm, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrisonName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PrisonName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PrisonName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Convicts Image", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input class="form-control" type="file" id="Image" name="uploadFile" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </fieldset>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CMRS/Views/Convicts/Fulldet.cshtml
@model CMRS.Models.Convict

@{
    ViewBag.Title = "Full Status";
    Layout = "~/Views/Shared/_LayoutPag.cshtml";
}

<h2>Full Convict Details</h2>


<div>
    <h4>Convict</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConvictName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConvictName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConvictAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConvictAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offense)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offense)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaseStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaseStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JailTerm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JailTerm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrisonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrisonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Action("Details", "Convicts", new { id = Model.Id })" width="50px" height="50px" />

        </dd>

    </dl>
   
    
  

    <p>
        @Html.ActionLink("Print", "PrintReport", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

CMRS/Views/Convicts/Index.cshtml
@model IEnumerable<CMRS.Models.Convict>



@using PagedList.Mvc;



@{
    ViewBag.Title = "Home-Convicts";
    Layout = "~/Views/Shared/_LayoutPag.cshtml";
}

<h2>Convicts</h2>



@using (Html.BeginForm("Index", "Convicts", FormMethod.Get))
{
        //the following are search options
   <b> Search Option: </b>
    @Html.RadioButton("option", "Name")  <text>Convict Name</text> 
    @Html.RadioButton("option", "Offense") <text> Crime </text>
    @Html.TextBox("search") <input  type ="submit" name ="submit" value ="Search"/>
        }

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ConvictName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConvictAge)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Offense)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CaseStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JailTerm)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrisonName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    { <tr> <td colspan ="6"> Matching Records not found </td>
    </tr>
    }
    else

    {

 foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ConvictName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConvictAge)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Offense)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CaseStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JailTerm)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrisonName)
        </td>
        <td>
        <img src="@Url.Action("Details", "Convicts", new { id = item.Id })" width="50px" height="50px" />
        </td>
       

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Fulldet", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}
    }
</table>

CMRS/Views/Convicts/PrintReport.cshtml
@model CMRS.Models.Convict

@{
    ViewBag.Title = "Full Status";
    Layout = "~/Views/Shared/_LayoutPag.cshtml";
}

<h2>Criminal Report</h2>


<div>
    <h4>Convict</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConvictName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConvictName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConvictAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConvictAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offense)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offense)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaseStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaseStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JailTerm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JailTerm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrisonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrisonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Action("Details", "Convicts", new { id = Model.Id })" width="50px" height="50px" />

        </dd>

    </dl>


    <p>
        <input type="button" id="btnPrint" value="Print" class="btn-primary" />
    </p>

    <p> 
            @Html.ActionLink("Cancel", "Index")

    </p>
</div>

@section scripts
{
    <script>
        $(function() {
            $("#btnPrint").click(function () {
                window.print()

            });
        });
    </script>
}